# Generated by Django 5.1.8 on 2025-04-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0002_email_in_reply_to_email_references_thread_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaddress',
            name='use_ssl',
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='use_tls',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='imap_connection_type',
            field=models.CharField(choices=[('plain', 'Plain (no encryption)'), ('ssl', 'SSL'), ('tls', 'TLS/STARTTLS')], default='ssl', max_length=10, verbose_name='IMAP connection type'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='smtp_connection_type',
            field=models.CharField(choices=[('plain', 'Plain (no encryption)'), ('ssl', 'SSL'), ('tls', 'TLS/STARTTLS')], default='ssl', max_length=10, verbose_name='SMTP connection type'),
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='smtp_port',
            field=models.PositiveIntegerField(default=465, verbose_name='SMTP port'),
        ),
    ]
