# Generated by Django 5.1.8 on 2025-04-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0003_remove_emailaddress_use_ssl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaddress',
            name='idle_folder',
            field=models.CharField(default='INBOX', help_text='IMAP folder to monitor with IDLE', max_length=255, verbose_name='IDLE folder'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='use_idle',
            field=models.BooleanField(default=False, help_text='Enable real-time synchronization using IMAP IDLE', verbose_name='use IDLE for real-time sync'),
        ),
    ]
